### ISSUE TITLE
Error at every startup but works after a stop start

### ISSUE THREAD

**Issue by Blackflames64** [highvoltz/HBRelog#22]
Hello,

Whenever I start a profile, any profile, I get the following error:

`[6:44:17 AM] BF: Questing: ********* Tasks ***********
[6:44:17 AM] BF: Questing: ********* End of Task list ***********
[6:44:18 AM] BF: Questing: Starting E:\World of Warcraft\Wow.exe
[6:44:19 AM] BF: Questing: Waiting for Wow to start
[6:44:20 AM] System.InvalidOperationException: Cannot process request because the process (9976) has exited.
   at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.OpenProcessHandle(Int32 access)
   at System.Diagnostics.Process.get_Handle()
   at HighVoltz.HBRelog.Utility.Is64BitProcess(Process proc)
   at HighVoltz.HBRelog.WoW.WowLockToken.StartWoW()
   at HighVoltz.HBRelog.WoW.States.StartWowState.Run()
   at HighVoltz.HBRelog.FiniteStateMachine.FiniteStateMachine.Engine.Pulse()
   at HighVoltz.HBRelog.WoW.WowManager.Pulse()
   at HighVoltz.HBRelog.TaskManager.Pulse()
   at HighVoltz.HBRelog.HbRelogManager.DoWork()
[6:44:21 AM] System.InvalidOperationException: Cannot process request because the process (9976) has exited.
   at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.OpenProcessHandle(Int32 access)
   at System.Diagnostics.Process.get_Handle()
   at HighVoltz.HBRelog.Utility.Is64BitProcess(Process proc)
   at HighVoltz.HBRelog.WoW.WowLockToken.StartWoW()
   at HighVoltz.HBRelog.WoW.States.StartWowState.Run()
   at HighVoltz.HBRelog.FiniteStateMachine.FiniteStateMachine.Engine.Pulse()
   at HighVoltz.HBRelog.WoW.WowManager.Pulse()
   at HighVoltz.HBRelog.TaskManager.Pulse()
   at HighVoltz.HBRelog.HbRelogManager.DoWork()
[6:44:22 AM] System.InvalidOperationException: Cannot process request because the process (9976) has exited.
   at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.OpenProcessHandle(Int32 access)
   at System.Diagnostics.Process.get_Handle()
   at HighVoltz.HBRelog.Utility.Is64BitProcess(Process proc)
   at HighVoltz.HBRelog.WoW.WowLockToken.StartWoW()
   at HighVoltz.HBRelog.WoW.States.StartWowState.Run()
   at HighVoltz.HBRelog.FiniteStateMachine.FiniteStateMachine.Engine.Pulse()
   at HighVoltz.HBRelog.WoW.WowManager.Pulse()
   at HighVoltz.HBRelog.TaskManager.Pulse()
   at HighVoltz.HBRelog.HbRelogManager.DoWork()`

Once I stop it, and start it again, it works perfectly **EXCEPT** after leaving it on for a long time, it won't let me open HBRelog, it keeps minimizing.

**Comment by Blackflames64** [comment]
Still getting this error.
